"""Manage the .archviewignore file: default patterns and add/remove/list."""

from __future__ import annotations

from pathlib import Path

IGNORE_FILENAME = ".archviewignore"

# Trailing slash = match the directory only, never a same-named file (build.py).
DEFAULT_IGNORE_PATTERNS = [
    ".archview/",
    ".venv/",
    "venv/",
    "__pycache__/",
    "node_modules/",
    ".git/",
    "build/",
    "dist/",
    "*.egg-info/",
    ".tox/",
    ".mypy_cache/",
    ".pytest_cache/",
    ".ruff_cache/",
]


def ignore_file_path(project_dir: Path) -> Path:
    return project_dir / IGNORE_FILENAME


def ensure_default_ignore_file(project_dir: Path) -> Path:
    ignore_file = ignore_file_path(project_dir)
    if ignore_file.exists():
        return ignore_file
    header = (
        "# Auto-generated by archview. Folders/patterns to exclude from "
        "analysis (one per line).\n"
    )
    ignore_file.write_text(header + "\n".join(DEFAULT_IGNORE_PATTERNS) + "\n")
    print(f"Created default {IGNORE_FILENAME}")
    return ignore_file


def _read_patterns(ignore_file: Path) -> list[str]:
    if not ignore_file.exists():
        return []
    lines = ignore_file.read_text().splitlines()
    return [line for line in lines if line.strip() and not line.strip().startswith("#")]


def cmd_ignore(args) -> None:
    project_dir = Path(args.project_dir).resolve()
    ignore_file = ignore_file_path(project_dir)

    if args.list:
        patterns = _read_patterns(ignore_file)
        if not patterns:
            print("No patterns in .archviewignore")
        else:
            print(f"{ignore_file}:")
            for p in patterns:
                print(f"  {p}")
        return

    if args.remove:
        if not ignore_file.exists():
            print("No .archviewignore file found")
            return
        lines = ignore_file.read_text().splitlines()
        new_lines = [line for line in lines if line.strip() != args.remove]
        if len(new_lines) == len(lines):
            print(f"Pattern not found: {args.remove}")
            return
        ignore_file.write_text("\n".join(new_lines) + "\n")
        print(f"Removed: {args.remove}")
        return

    if not args.patterns:
        print("Usage: archview ignore <pattern> [pattern ...]")
        print("       archview ignore --list")
        print("       archview ignore --remove <pattern>")
        return

    existing = _read_patterns(ignore_file)
    added = []
    for pattern in args.patterns:
        if pattern in existing:
            print(f"Already ignored: {pattern}")
        else:
            added.append(pattern)

    if added:
        write_header = not ignore_file.exists() or ignore_file.stat().st_size == 0
        with ignore_file.open("a") as f:
            if write_header:
                f.write("# Folders/patterns to exclude from analysis (one per line)\n")
            for p in added:
                f.write(p + "\n")
        for p in added:
            print(f"Added: {p}")
